services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
  pgadmin:
    image: pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
    ports:
      - "5001:80"
      
volumes:
  postgresdata: